name: Build and Deploy React App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install and Build
        working-directory: ./dmahon-website
        run: |
          npm install
          npm run build
          
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dmahon-website/dist'  # Your build output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
