name: Deploy React App to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js specifically in your website folder
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      # Build React app
      - name: Install and Build
        working-directory: ./dmahon-website
        run: |
          npm install
          npm run build

      # Verify build output (debugging)
      - name: List build files
        run: ls -R ./dmahon-website/dist || echo "Build failed - no dist directory"

      # Deploy using modern GitHub Pages action
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dmahon-website/dist'  # Your actual build output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2