name: Deploy React App to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install and Build
        working-directory: ./dmahon-website
        run: |
          npm install
          npm run build

      - name: Copy index.html to 404.html
        run: cp ./dmahon-website/dist/index.html ./dmahon-website/dist/404.html

      - name: List build files
        run: ls -R ./dmahon-website/dist || echo "Build failed - no dist directory"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dmahon-website/dist'

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
